### PR TITLE
modified head.html to fix Title config bug

### PR DESCRIPTION
**Pull request by aescay**

### CODE REVIEW

**Comment by aescay** [comment]
Hi @eueung hope you can merge this in to fix the bug with Title not working

**Comment by dixonge** [comment]
FYI, @eueung has not made any commits to this repo in over 18 months. Keep a fork or a local copy and update as needed.

**Comment by aescay** [comment]
Yeah I noticed this @dixonge. Thanks for letting me know! Was hoping he would merge this simple fix but ohh well, I guess I'll just stick to my forked version for now haha

**Comment by aescay** [comment]
abandoning since the owner is not actively maintaining this project

**Pull request closed without merging**
